"use client";
import { DragEvent, FormEvent, useEffect, useState } from "react";
import { FileText, UploadCloud } from "lucide-react";

type Project = { id: string; name: string };
export default function UploadClient() {
  const [file, setFile] = useState<File | null>(null); const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/projects").then(r => r.json()).then(data => { const items = data.projects || []; setProjects(items); const requested = new URLSearchParams(window.location.search).get("projectId"); if (requested && items.some((project: Project) => project.id === requested)) setProjectId(requested); }).catch(() => setProjects([])); }, []);
  function choose(candidate: File | undefined) { if (!candidate) return; setMessage(""); setFile(candidate); }
  function drop(event: DragEvent<HTMLLabelElement>) { event.preventDefault(); choose(event.dataTransfer.files[0]); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!file) { setMessage("Choose a document first."); return; } setBusy(true); setMessage(""); const body = new FormData(); body.append("file", file); if (projectId) body.append("projectId", projectId); try { const response = await fetch("/api/analyses", { method: "POST", body }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Upload failed"); setMessage("Upload received. Analysis is queued for processing."); setFile(null); } catch (error) { setMessage(error instanceof Error ? error.message : "Upload failed"); } finally { setBusy(false); } }
  return <section className="py-7"><div className="mb-7"><p className="text-xs font-medium uppercase tracking-[0.17em] text-[#e3b341]">Workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">New analysis</h1><p className="mt-2 max-w-xl text-sm text-[#8b949e]">Upload a requirements document and run the deterministic ReqGuard quality engine.</p></div><form onSubmit={submit} className="max-w-3xl space-y-5"><label onDragOver={e => e.preventDefault()} onDrop={drop} className="flex min-h-64 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-[#e3b341]/40 bg-[#e3b341]/[0.03] p-8 text-center transition hover:bg-[#e3b341]/[0.07]"><input type="file" accept=".txt,.csv,.json,text/plain,text/csv,application/json" className="sr-only" onChange={e => choose(e.target.files?.[0])} /><UploadCloud size={32} className="text-[#e3b341]" /><p className="mt-4 text-sm font-medium text-white">{file ? file.name : "Drop your requirements document here"}</p><p className="mt-2 text-xs text-[#737b85]">TXT, CSV, or JSON · Maximum 20 MB</p></label><div className="rounded-xl border border-white/[0.08] bg-white/[0.025] p-5"><label className="block text-xs text-[#8b949e]">Project (optional)<select value={projectId} onChange={e => setProjectId(e.target.value)} className="mt-2 h-10 w-full rounded-lg border border-white/[0.09] bg-black/30 px-3 text-sm text-white outline-none"><option value="">Workspace analysis</option>{projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>{file && <div className="mt-4 flex items-center gap-3 rounded-lg bg-black/30 p-3"><FileText size={18} className="text-[#e3b341]" /><span className="truncate text-sm text-[#d8dee4]">{file.name}</span><span className="ml-auto text-xs text-[#737b85]">{(file.size / 1024 / 1024).toFixed(2)} MB</span></div>}<p className="mt-4 text-xs text-[#8b949e]">{message}</p><button disabled={busy} className="mt-4 h-10 rounded-lg bg-[#e3b341] px-5 text-xs font-semibold text-[#171006] disabled:opacity-60">{busy ? "Analyzing..." : "Start analysis"}</button></div></form></section>;
}
