"use client";

import { useEffect, useMemo, useState } from "react";
import { BookOpen, ChevronRight, FileText, MessageCircle, Search, Send, Ticket, ThumbsDown, ThumbsUp } from "lucide-react";

type Article = { id: string; title: string; slug: string; category: string; kind: string; excerpt: string; content: string; createdAt: string; updatedAt: string };
const nav = [{ label: "Help Articles", kind: "article", icon: BookOpen }, { label: "Documentation", kind: "documentation", icon: FileText }, { label: "Tutorials", kind: "tutorial", icon: ChevronRight }, { label: "FAQs", kind: "faq", icon: MessageCircle }];

export default function SupportPortal({ initialArticles, categories }: { initialArticles: Article[]; categories: string[] }) {
  const [articles, setArticles] = useState(initialArticles);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [kind, setKind] = useState<string | null>(null);
  const [selected, setSelected] = useState<Article | null>(null);
  const [ticketOpen, setTicketOpen] = useState(false);
  const [tickets, setTickets] = useState<{ id: string; subject: string; status: string; conversation?: { messages: { id: string; body: string; createdAt: string }[] } }[]>([]);
  useEffect(() => { fetch("/api/support/tickets").then(async (response) => response.ok && setTickets((await response.json()).tickets)); }, []);
  const filtered = useMemo(() => articles.filter((a) => (!kind || a.kind === kind) && (!category || category === "All" || a.category === category)), [articles, kind, category]);
  async function search(value: string) {
    setQuery(value);
    const response = await fetch(`/api/support/articles?q=${encodeURIComponent(value)}${category !== "All" ? `&category=${encodeURIComponent(category)}` : ""}`);
    if (response.ok) setArticles((await response.json()).articles);
  }
  async function feedback(articleId: string, helpful: boolean) {
    await fetch("/api/support/feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ articleId, helpful }) });
  }
  return <div className="py-7">
    <div className="mb-8"><p className="text-xs font-medium uppercase tracking-[0.17em] text-[#e3b341]">Support center</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">How can we help?</h1><p className="mt-2 text-sm text-[#8b949e]">Search the ReqGuard knowledge base or start a conversation with our support team.</p></div>
    <div className="mb-7 flex max-w-3xl items-center gap-3 rounded-xl border border-white/[0.1] bg-white/[0.04] px-4 py-3"><Search size={19} className="text-[#e3b341]" /><input value={query} onChange={(e) => search(e.target.value)} placeholder="Search articles, documentation, and FAQs..." className="w-full bg-transparent text-sm text-white outline-none placeholder:text-[#68717d]" /></div>
    <div className="grid gap-7 lg:grid-cols-[210px_1fr]">
      <aside className="space-y-1">{nav.map(({ label, kind: navKind, icon: Icon }) => <button key={label} onClick={() => { setKind(navKind); setCategory("All"); }} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm ${kind === navKind ? "bg-[#e3b341]/10 text-[#f7d774]" : "text-[#8b949e] hover:bg-white/[0.04] hover:text-white"}`}><Icon size={17} />{label}</button>)}<button onClick={() => setTicketOpen(true)} className="mt-5 flex w-full items-center gap-3 rounded-lg border border-[#e3b341]/30 px-3 py-2.5 text-left text-sm text-[#f7d774]"><Ticket size={17} />Contact support</button><div className="mt-7 border-t border-white/[0.08] pt-5"><p className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.15em] text-[#59616a]">Categories</p>{["All", ...categories].map((item) => <button key={item} onClick={() => { setCategory(item); setKind(null); }} className={`block w-full rounded-lg px-3 py-2 text-left text-xs ${category === item ? "text-[#e3b341]" : "text-[#8b949e] hover:text-white"}`}>{item}</button>)}</div></aside>
      <section><div className="mb-4 flex items-center justify-between"><p className="text-xs text-[#68717d]">{filtered.length} resources</p><button onClick={() => setTicketOpen(true)} className="flex items-center gap-2 rounded-lg bg-[#e3b341] px-3 py-2 text-xs font-semibold text-black"><Ticket size={15} />New ticket</button></div><div className="grid gap-3 md:grid-cols-2">{filtered.map((article) => <article key={article.id} className="rounded-xl border border-white/[0.08] bg-white/[0.025] p-5"><div className="flex items-center justify-between"><span className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#e3b341]">{article.category}</span><span className="text-[10px] uppercase text-[#68717d]">{article.kind}</span></div><button onClick={() => setSelected(article)} className="mt-3 text-left text-sm font-semibold text-white hover:text-[#f7d774]">{article.title}</button><p className="mt-2 text-sm leading-6 text-[#8b949e]">{article.excerpt}</p><button onClick={() => setSelected(article)} className="mt-4 flex items-center gap-1 text-xs text-[#e3b341]">Read article <ChevronRight size={14} /></button></article>)}</div>{filtered.length === 0 && <div className="rounded-xl border border-dashed border-white/[0.12] p-10 text-center text-sm text-[#8b949e]">No matching resources. Try another search or contact support.</div>}</section>
    </div>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4" onClick={() => setSelected(null)}><article className="max-h-[80vh] w-full max-w-2xl overflow-auto rounded-2xl border border-white/[0.1] bg-[#101010] p-6" onClick={(e) => e.stopPropagation()}><span className="text-xs uppercase tracking-[0.15em] text-[#e3b341]">{selected.category} · {selected.kind}</span><h2 className="mt-3 text-2xl font-semibold">{selected.title}</h2><p className="mt-5 whitespace-pre-line text-sm leading-7 text-[#b0b8c2]">{selected.content}</p><div className="mt-7 flex items-center gap-2 border-t border-white/[0.08] pt-5"><span className="mr-2 text-xs text-[#8b949e]">Was this helpful?</span><button onClick={() => feedback(selected.id, true)} className="flex items-center gap-1 rounded-lg border border-white/[0.1] px-3 py-2 text-xs text-[#8b949e] hover:text-white"><ThumbsUp size={14} /> Helpful</button><button onClick={() => feedback(selected.id, false)} className="flex items-center gap-1 rounded-lg border border-white/[0.1] px-3 py-2 text-xs text-[#8b949e] hover:text-white"><ThumbsDown size={14} /> Not helpful</button></div></article></div>}
    {tickets.length > 0 && <section className="mt-10"><h2 className="mb-3 text-lg font-semibold">Your support conversations</h2><div className="space-y-3">{tickets.map((ticket) => <TicketConversation key={ticket.id} ticket={ticket} onMessage={(message) => setTickets((items) => items.map((item) => item.id === ticket.id ? { ...item, conversation: { messages: [...(item.conversation?.messages || []), message] } } : item))} />)}</div></section>}
    {ticketOpen && <TicketForm onClose={() => setTicketOpen(false)} onCreated={(ticket) => { setTickets((items) => [ticket, ...items]); setTicketOpen(false); }} />}
  </div>;
}

function TicketConversation({ ticket, onMessage }: { ticket: { id: string; subject: string; status: string; conversation?: { messages: { id: string; body: string; createdAt: string }[] } }; onMessage: (message: { id: string; body: string; createdAt: string }) => void }) {
  const [body, setBody] = useState("");
  async function send(e: React.FormEvent) { e.preventDefault(); const response = await fetch("/api/support/messages", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ticketId: ticket.id, body }) }); if (response.ok) { onMessage((await response.json()).message); setBody(""); } }
  return <article className="rounded-xl border border-white/[0.08] bg-white/[0.025] p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">{ticket.subject}</h3><span className="text-[10px] uppercase text-[#e3b341]">{ticket.status.replace("_", " ")}</span></div><div className="mt-3 space-y-2">{ticket.conversation?.messages.map((message) => <p key={message.id} className="rounded-lg bg-white/[0.05] px-3 py-2 text-xs leading-5 text-[#b0b8c2]">{message.body}</p>)}</div><form onSubmit={send} className="mt-3 flex gap-2"><input required value={body} onChange={(e) => setBody(e.target.value)} placeholder="Reply to support..." className="min-w-0 flex-1 rounded-lg border border-white/[0.1] bg-white/[0.04] px-3 py-2 text-xs outline-none" /><button className="rounded-lg bg-[#e3b341] px-3 text-black"><Send size={14} /></button></form></article>;
}

function TicketForm({ onClose, onCreated }: { onClose: () => void; onCreated: (ticket: { id: string; subject: string; status: string; conversation?: { messages: { id: string; body: string; createdAt: string }[] } }) => void }) {
  const [form, setForm] = useState({ subject: "", category: "Getting Started", priority: "NORMAL", description: "" });
  const [attachment, setAttachment] = useState("");
  async function submit(e: React.FormEvent) { e.preventDefault(); const response = await fetch("/api/support/tickets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, attachment }) }); if (response.ok) onCreated((await response.json()).ticket); }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl border border-white/[0.1] bg-[#101010] p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Contact support</h2><button type="button" onClick={onClose} className="text-sm text-[#8b949e]">Close</button></div><input required placeholder="Subject" value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} className="mt-6 w-full rounded-lg border border-white/[0.1] bg-white/[0.04] px-3 py-3 text-sm outline-none" /><div className="mt-3 grid grid-cols-2 gap-3"><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className="rounded-lg border border-white/[0.1] bg-[#151515] px-3 py-3 text-sm"><option>Getting Started</option><option>Analysis</option><option>Team</option><option>Reports</option><option>Billing</option><option>Security</option></select><select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })} className="rounded-lg border border-white/[0.1] bg-[#151515] px-3 py-3 text-sm"><option value="LOW">Low</option><option value="NORMAL">Normal</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select></div><textarea required rows={5} placeholder="Describe the issue, including project or analysis details..." value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-3 w-full rounded-lg border border-white/[0.1] bg-white/[0.04] px-3 py-3 text-sm outline-none" /><input type="file" onChange={(e) => setAttachment(e.target.files?.[0]?.name || "")} className="mt-3 w-full text-xs text-[#8b949e]" /><button className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-[#e3b341] py-3 text-sm font-semibold text-black"><Send size={15} />Create ticket</button></form></div>;
}
