ALTER TABLE "Report"
  ADD COLUMN "format" TEXT NOT NULL DEFAULT 'CSV',
  ADD COLUMN "snapshot" JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
